### ISSUE TITLE
Potential insights regarding a StackOverflow review

### ISSUE THREAD

**Issue by 2xB** [2xB/talk#1]
@AzyCrw4282 @JeremyCaney
Hey! Feel free to ignore this, but I'd be happy about insight nevertheless!
On [this StackOverflow review](https://stackoverflow.com/review/suggested-edits/27980993), you rejected my edit on a post because it `was intended to address the author of the post `. As I am not that active as an author on SO, I still have much to learn about when to post what how, therefore I wonder: I actually intended this to be an information for viewers of this post, not the author. It probably won't help the author - they likely have written their application and moved on. It's a post from 2015 after all! I just found that post, because I was in need of exactly what they did and thought I might as well help others traveling there with simpler code. I didn't want to replace their code as it might still be important to people using older versions of the library. The code snippet had multiple lines and was therefore impractical for a comment. Also, I think a new answer would hardly make sense, because it would just be their current workaround with these three lines updated. It still stays basically the same workaround. How would you approach this situation, i.e. under these circumstances, is what I did reasonable or is there a better way?

Anyways, wish you a happy new year!

**Comment by AzyCrw4282** [comment]
@2xB Thanks for reaching out on this, I am happy to explain why I gave 'Reject' (and I am pretty sure the same reasons would also apply from the side of @jeremy). Firstly, answers that solve the required problems are not required to be updated based on incremented versions; as you would understand that if this was the case then a majority of the answers on StackOverflow will need to be updated frequently. 
Answers that are for the newer version are often left as comments (in the rarest cases), and in your case, the 3 lines would be sufficient enough to do that, and I would recommend this over leaving it as an answer.
Also, understand that the reviewing process from the side of the reviewer for each edit is a matter of `0-10` seconds (or less) involved in assessing if this improves the post or not, so often based on the first look the decisions are made so that is how you are likely to get mixtures of accepted/rejected.

I hope it makes sense and do continue to contribute to the site.

**Comment by 2xB** [comment]
@AzyCrw4282 Somewhat late, but anyways: Thank you for that detailed answer! Learning about the process from the other side is quite interesting.

To put this in context from my side: Since there are negative effects directly following from too many rejected edits - such as edit suspension and I believe being unable to review edits oneself -, and since I believe to already be careful about when to suggest an edit, edit rejections are somewhat difficult for me: Despite my best efforts, two out of the four edits I suggested so far were rejected. I understand though that this is of course a rather small amount of edit suggestions and therefore far from statistically significant.

In this specific case, I believe it might be difficult to put multi-line code into a comment. So for the future, I do take from your response that I have to take more care about showing reviewers immediately why an edit is important. And when edits are rejected, I hopefully learn what is important to consider for the reviewing process in the future.

Thank you once more very much for the insights given!
